modLoader="javafml"
loaderVersion="[41,)"
license="GNU General Public License v3.0"

[[mods]]
    modId="scorchedguns"
    version="0.7.2"
    displayName="Scorched Guns"
    authors="Ribs"
    credits="Mr. Pineapple and Mr. Crayfish"
    description="Guns :)"

[[dependencies.scorchedguns]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scorchedguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scorchedguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.2.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scorchedguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.3.2,)"
    ordering="NONE"
    side="BOTH"


